---
- name: Check if downloadable archive exists
  stat: path={{ downloads }}/mahout-{{ mahout_version }}-cdh{{ cdh_version }}.tar.gz
  register: archive

- name: Get Mahout binary
  get_url: url=http://archive.cloudera.com/cdh{{ cdh_major }}/cdh/{{ cdh_major }}/mahout-{{ mahout_version }}-cdh{{ cdh_version }}.tar.gz dest={{ downloads }}
  when: archive.stat.exists == false
  tags:
  - download

- name: Check if unpacked archive exists
  stat: path={{ install_dir }}/mahout-{{ mahout_version }}-cdh{{ cdh_version }}
  register: unpacked

- name: Unarchive Mahout binary
  unarchive: copy=no src={{ downloads }}/mahout-{{ mahout_version }}-cdh{{ cdh_version }}.tar.gz dest={{ install_dir }}
  when: unpacked.stat.exists == false
  tags:
  - extract

